name: Push latest version
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - uses: actions/checkout@master
      - name: Push to GitHub Packages latest tag
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: paprickar/csi-driver/hcloud-csi-driver
          tag_with_ref: true